# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-13 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ch_goods', '0001_initial'),
        ('ch_supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adv1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advpic1', models.ImageField(blank=True, null=True, upload_to='adv_goods', verbose_name='\u9996\u9875\u8df3\u8f6c\u56fe\u7247')),
                ('advpic2', models.ImageField(blank=True, help_text='\u56fe\u7247\u5927\u5c0f\u4e0d\u8d85\u8fc7200kb\uff0c\u9ad8360px\uff0c\u5bbd1090px', null=True, upload_to='adv_goods', verbose_name='\u6b21\u9875\u56fe\u7247')),
                ('advnum', models.IntegerField(default=1, help_text='\u6bcf\u671f30\u5929', verbose_name='\u4f4d\u7f6e\u671f\u6570')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='\u5efa\u7acb\u65f6\u95f4')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('advgoods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ch_goods.goodsinfo', verbose_name='\u5546\u54c1')),
                ('advgt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ch_goods.goodstype', verbose_name='\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u4f4d\u7f6e\u5185\u5bb9',
                'verbose_name_plural': '\u9996\u9875\u4f4d\u7f6e\u5185\u5bb9\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='adv1type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advtitle', models.CharField(max_length=11, verbose_name='\u9996\u9875\u4f4d\u7f6e\u540d\u79f0')),
                ('advposition1', models.IntegerField(verbose_name='\u9996\u4f4d')),
                ('advposition2', models.IntegerField(verbose_name='\u6b21\u4f4d')),
                ('advprice', models.DecimalField(decimal_places=2, default=10000.0, max_digits=9, verbose_name='\u4f4d\u7f6e\u5355\u4ef7:RMB/\u671f')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u4f4d\u7f6e',
                'verbose_name_plural': '\u9996\u9875\u4f4d\u7f6e\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='adv1',
            name='advtp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adv_tp', to='ch_adv.adv1type', verbose_name='\u9996\u9875\u4f4d\u7f6e'),
        ),
        migrations.AddField(
            model_name='adv1',
            name='advuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ch_supplier.SupplierInfo', verbose_name='\u5185\u5bb9\u53d1\u5e03\u4eba'),
        ),
    ]
