# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-13 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch_adv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv1type',
            name='advtitle',
            field=models.CharField(max_length=32, verbose_name='\u9996\u9875\u4f4d\u7f6e\u540d\u79f0'),
        ),
    ]
