# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-14 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ch_adv', '0002_auto_20180513_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv1',
            name='is_Delete',
            field=models.BooleanField(default=0, verbose_name='\u662f\u5426\u53d1\u5e03'),
        ),
        migrations.AddField(
            model_name='adv1type',
            name='ctime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5efa\u7acb\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='adv1type',
            name='is_Delete',
            field=models.BooleanField(default=0, verbose_name='\u662f\u5426\u53d1\u5e03'),
        ),
        migrations.AddField(
            model_name='adv1type',
            name='utime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='adv1',
            name='advuser',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='ch_supplier.SupplierInfo', verbose_name='\u5185\u5bb9\u53d1\u5e03\u4eba'),
        ),
    ]
