# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-14 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch_adv', '0003_auto_20180514_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv1type',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u5efa\u7acb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='adv1type',
            name='utime',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
