# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-14 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch_adv', '0005_auto_20180514_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv1',
            name='advstatus',
            field=models.IntegerField(choices=[(0, '\u9884\u5907'), (1, '\u4e0a\u7ebf'), (2, '\u5230\u671f\u4e0b\u7ebf')], default=0, verbose_name='\u7248\u9762\u72b6\u6001'),
        ),
    ]
