# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-13 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=16, unique=True, verbose_name='\u54c1\u724c\u540d\u79f0')),
                ('bstory', models.TextField(max_length=128, verbose_name='\u54c1\u724c\u6545\u4e8b')),
                ('bpic', models.ImageField(upload_to='supplier', verbose_name='\u5ba3\u4f20\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u54c1\u724c',
                'verbose_name_plural': '\u54c1\u724c\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='SupplierInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stype', models.IntegerField(choices=[(1, '\u4e2a\u4eba'), (2, '\u670d\u52a1\u5546'), (3, '\u5236\u9020\u5546')], verbose_name='\u5546\u5bb6\u7c7b\u578b')),
                ('sname', models.CharField(max_length=32, unique=True, verbose_name='\u5546\u5bb6\u540d\u79f0')),
                ('ssynopsis', models.TextField(max_length=128, verbose_name='\u5546\u5bb6\u7b80\u4ecb')),
                ('saccount', models.CharField(max_length=32, unique=True, verbose_name='\u5546\u5bb6\u8d22\u52a1\u8d26\u53f7')),
                ('saddress', models.CharField(max_length=32, verbose_name='\u5546\u5bb6\u5730\u5740')),
                ('sphon', models.CharField(max_length=20, verbose_name='\u5546\u5bb6\u7535\u8bdd')),
                ('scontact', models.CharField(max_length=20, verbose_name='\u5546\u5bb6\u8054\u7cfb\u4eba')),
                ('is_Delete', models.BooleanField(default=False, verbose_name='\u5220\u9664')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='\u5efa\u7acb\u65f6\u95f4')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5546\u5bb6',
                'verbose_name_plural': '\u5546\u5bb6\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='suser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suser', models.CharField(max_length=16, unique=True, verbose_name='\u8d26\u53f7')),
                ('spwd', models.CharField(max_length=32, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u5546\u5bb6\u8d26\u53f7',
                'verbose_name_plural': '\u5546\u5bb6\u8d26\u53f7\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='supplierinfo',
            name='spuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_supplier', to='ch_supplier.suser', verbose_name='\u5546\u5bb6\u8d26\u53f7'),
        ),
        migrations.AddField(
            model_name='brand',
            name='bsupport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_brand', to='ch_supplier.SupplierInfo', verbose_name='\u6240\u5c5e\u5236\u9020\u5546'),
        ),
    ]
