# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-13 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=16, verbose_name='\u6536\u8d27\u4eba')),
                ('lphon', models.CharField(max_length=11, verbose_name='\u7535\u8bdd')),
                ('larea', models.CharField(default='\u5317\u4eac\u5e02\u6d77\u6dc0\u533a', max_length=32, verbose_name='\u6240\u5728\u5730\u533a')),
                ('laddress', models.CharField(max_length=128, verbose_name='\u8be6\u7ec6\u5730\u5740')),
                ('lyoubian', models.CharField(default='', max_length=6, verbose_name='\u90ae\u7f16')),
                ('lctime', models.DateTimeField(auto_now_add=True, verbose_name='\u5efa\u7acb\u65f6\u95f4')),
                ('lutime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('is_Delete', models.BooleanField(default=False, verbose_name='\u5220\u9664\u8be5\u5730\u5740')),
                ('is_Default', models.BooleanField(default=False, verbose_name='\u9ed8\u8ba4')),
            ],
            options={
                'verbose_name': '\u5730\u5740',
                'verbose_name_plural': '\u6536\u8d27\u5730\u5740\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=64, verbose_name='\u7528\u6237\u540d')),
                ('upwd', models.CharField(max_length=64, verbose_name='\u5bc6\u7801')),
                ('uemail', models.EmailField(max_length=64, verbose_name='\u90ae\u7bb1')),
                ('uphon', models.CharField(default='', max_length=16, verbose_name='\u7535\u8bdd')),
                ('uctime', models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('uuptime', models.DateTimeField(auto_now=True)),
                ('is_Delete', models.BooleanField(default=False, verbose_name='\u5220\u9664\u8be5\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237\u8868',
            },
        ),
        migrations.CreateModel(
            name='wxuserinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxuin', models.CharField(max_length=16, verbose_name='\u6807\u8bc6')),
                ('wxnickname', models.CharField(max_length=32, verbose_name='\u6635\u79f0')),
                ('wxinfo', models.TextField(max_length=1280, verbose_name='\u7528\u6237\u4fe1\u606f')),
                ('uctime', models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('uuptime', models.DateTimeField(auto_now=True)),
                ('wxuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ch_user.UserInfo', verbose_name='\u7528\u6237id')),
            ],
            options={
                'verbose_name': '\u5fae\u4fe1\u7528\u6237',
                'verbose_name_plural': '\u5fae\u4fe1\u7528\u6237\u8868',
            },
        ),
        migrations.AddField(
            model_name='logisticsinfo',
            name='luser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lg', to='ch_user.UserInfo', verbose_name='\u7528\u6237'),
        ),
    ]
