# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-13 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ch_supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crfdinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctarget', models.IntegerField(verbose_name='\u76ee\u6807\u91d1\u989d')),
                ('cmax', models.IntegerField(default=1000, verbose_name='\u9650\u5236\u6570\u91cf')),
                ('cterm', models.IntegerField(default=30, verbose_name='\u76ee\u6807\u671f\u9650')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='\u5efa\u7acb\u65f6\u95f4')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('cstatus', models.IntegerField(choices=[(0, '\u7ed3\u675f\u4f17\u7b79'), (1, '\u6b63\u5728\u4f17\u7b79')], default=0, verbose_name='\u4f17\u7b79\u72b6\u6001')),
                ('cusernum', models.IntegerField(verbose_name='\u652f\u6301\u4eba\u6570')),
                ('cclick', models.IntegerField(verbose_name='\u70b9\u51fb\u6570')),
                ('is_Delete', models.BooleanField(default=0, verbose_name='\u662f\u5426\u53d1\u5e03')),
            ],
            options={
                'verbose_name': '\u4f17\u7b79',
                'verbose_name_plural': '\u4f17\u7b79\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='goodscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gclick', models.IntegerField(verbose_name='\u70b9\u51fb\u6570')),
                ('gevalu', models.IntegerField(verbose_name='\u8bc4\u8bba\u6570')),
                ('gorder', models.IntegerField(verbose_name='\u9500\u552e\u6570')),
                ('gback', models.IntegerField(verbose_name='\u9000\u8d27\u6570')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u7edf\u8ba1',
                'verbose_name_plural': '\u5546\u54c1\u7edf\u8ba1\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='goodsimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpic', models.ImageField(upload_to='ch_goods', verbose_name='\u4ea7\u54c1\u56fe\u7247')),
                ('gpd', models.IntegerField(verbose_name='\u56fe\u7247\u5bbd')),
                ('gph', models.IntegerField(verbose_name='\u56fe\u7247\u9ad8')),
                ('gppoint', models.IntegerField(verbose_name='\u56fe\u7247\u4f4d\u7f6e')),
            ],
            options={
                'verbose_name': '\u56fe\u7247',
                'verbose_name_plural': '\u56fe\u7247\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='goodsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=32, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('gscode', models.CharField(max_length=32, null=True, verbose_name='\u5236\u9020\u7f16\u7801')),
                ('gmaterials', models.IntegerField(choices=[(1, '\u9ad8\u5cad\u571f'), (2, '\u7c98\u571f'), (3, '\u6c27\u5316\u94dd'), (4, '\u9ad8\u5cad\u571f+\u7c98\u571f'), (5, '\u9ad8\u5cad\u571f+\u6c27\u5316\u94dd'), (6, '\u7c98\u571f+\u6c27\u5316\u94dd'), (7, '\u9ad8\u5cad\u571f+\u7c98\u571f+\u6c27\u5316\u94dd'), (8, '\u6c27\u5316\u94dd')], default=1, verbose_name='\u539f\u6599')),
                ('gtechnique', models.IntegerField(choices=[(1, '\u624b\u7ed8'), (2, '\u8d34\u82b1'), (3, '\u8f6c\u5370'), (4, '\u624b\u7ed8+\u8d34\u82b1'), (5, '\u624b\u7ed8+\u8f6c\u5370'), (6, '\u8d34\u82b1+\u8f6c\u5370'), (7, '\u624b\u7ed8+\u8d34\u82b1+\u8f6c\u5370'), (8, '\u5176\u5b83')], default=1, verbose_name='\u5de5\u827a')),
                ('gmax', models.IntegerField(verbose_name='\u4f9b\u5e94\u6570\u91cf')),
                ('gsynopsis', tinymce.models.HTMLField(verbose_name='\u4ea7\u54c1\u7b80\u4ecb')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='\u5efa\u7acb\u65f6\u95f4')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('gbrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g_brand', to='ch_supplier.brand', verbose_name='\u54c1\u724c')),
            ],
            options={
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='goodsmangent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gxprice', models.DecimalField(decimal_places=2, default=1.2, max_digits=4, verbose_name='\u9500\u552e\u5355\u4ef7\u7387')),
                ('is_Delete', models.BooleanField(default=False, verbose_name='\u5220\u9664')),
                ('gstatus', models.IntegerField(choices=[(0, '\u4e0b\u7ebf'), (1, '\u4e0a\u7ebf'), (2, '\u9884\u552e')], default=0, verbose_name='\u72b6\u6001')),
                ('grecommendation', models.BooleanField(default=False, verbose_name='\u63a8\u8350')),
                ('gcredit', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u79ef\u5206')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='\u5efa\u7acb\u65f6\u95f4')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('gmgoods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ch_goods.goodsinfo', verbose_name='\u5546\u54c1')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u7ba1\u7406',
                'verbose_name_plural': '\u5546\u54c1\u7ba1\u7406\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='goodstype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=16, verbose_name='\u5546\u54c1\u7c7b\u578b')),
                ('gcontext', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u7c7b\u578b\u63cf\u8ff0')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='\u5efa\u7acb\u65f6\u95f4')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('is_Delete', models.BooleanField(default=False, verbose_name='\u5220\u9664')),
                ('gtfk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gtty', to='ch_goods.goodstype', verbose_name='\u6240\u5c5e\u7236\u7c7b')),
            ],
            options={
                'verbose_name': '\u7c7b\u578b',
                'verbose_name_plural': '\u7c7b\u578b\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='packaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmateria', models.CharField(default='\u7eb8\u76d2', max_length=8, verbose_name='\u5305\u88c5\u6750\u8d28')),
                ('pw', models.IntegerField(verbose_name='\u957f')),
                ('pd', models.IntegerField(verbose_name='\u5bbd')),
                ('ph', models.IntegerField(verbose_name='\u9ad8')),
                ('punti', models.CharField(default='mm', max_length=4, verbose_name='\u5355\u4f4d')),
                ('ppic', models.ImageField(upload_to='ch_goods', verbose_name='\u5305\u88c5\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u5305\u88c5',
                'verbose_name_plural': '\u5305\u88c5\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='qixing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtitle', models.CharField(max_length=11, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5668\u578b',
                'verbose_name_plural': '\u5668\u578b\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='salesgoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sstart', models.DateTimeField(verbose_name='\u6d3b\u52a8\u5f00\u59cb\u65f6\u95f4')),
                ('send', models.DateTimeField(verbose_name='\u6d3b\u52a8\u7ed3\u675f\u65f6\u95f4')),
                ('stitle', models.CharField(max_length=16, verbose_name='\u6d3b\u52a8\u540d\u79f0')),
                ('sdiscount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='\u6298\u6263')),
            ],
            options={
                'verbose_name': '\u4fc3\u9500\u6d3b\u52a8',
                'verbose_name_plural': '\u4fc3\u9500\u6d3b\u52a8\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stitle', models.CharField(max_length=11, verbose_name='\u670d\u52a1\u627f\u8bfa')),
                ('sico', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u670d\u52a1\u56fe\u6807')),
                ('scont', models.CharField(blank=True, max_length=64, verbose_name='\u670d\u52a1\u7b80\u4ecb')),
            ],
            options={
                'verbose_name': '\u670d\u52a1',
                'verbose_name_plural': '\u670d\u52a1\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w', models.IntegerField(verbose_name='\u957f')),
                ('d', models.IntegerField(verbose_name='\u5bbd')),
                ('h', models.IntegerField(verbose_name='\u9ad8')),
                ('unti', models.CharField(default='mm', max_length=4, verbose_name='\u6d4b\u91cf\u5355\u4f4d')),
                ('oldsize', models.CharField(max_length=5, verbose_name='\u89c4\u683c')),
                ('oldunti', models.CharField(default='\u4ef6', max_length=5, verbose_name='\u89c4\u683c\u5355\u4f4d')),
                ('weight', models.IntegerField(verbose_name='\u91cd')),
                ('unit', models.CharField(default='kg', max_length=4, verbose_name='\u91cd\u91cf\u5355\u4f4d')),
                ('sprice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u89c4\u683c\u5355\u4ef7')),
                ('num', models.IntegerField(default=1, verbose_name='\u89c4\u683c\u6570\u91cf')),
                ('sgoods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_goods', to='ch_goods.goodsinfo', verbose_name='\u6240\u5c5e\u5546\u54c1')),
                ('sqixing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_qx', to='ch_goods.qixing', verbose_name='\u6240\u5c5e\u5668\u578b')),
            ],
            options={
                'verbose_name': '\u89c4\u683c\u5c3a\u5bf8',
                'verbose_name_plural': '\u5668\u578b\u89c4\u683c\u5c3a\u5bf8\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='goodsmangent',
            name='gmsales',
            field=models.ManyToManyField(blank=True, null=True, to='ch_goods.salesgoods', verbose_name='\u5546\u54c1\u4fc3\u9500'),
        ),
        migrations.AddField(
            model_name='goodsmangent',
            name='goodscrfd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ch_goods.crfdinfo', verbose_name='\u4f17\u7b79'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='goodstype',
            field=models.ManyToManyField(related_name='g_gt', to='ch_goods.goodstype', verbose_name='\u6240\u5c5e\u5546\u54c1\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gpack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_pk', to='ch_goods.packaging', verbose_name='\u5305\u88c5'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gserver',
            field=models.ManyToManyField(related_name='g_sr', to='ch_goods.server', verbose_name='\u670d\u52a1\u627f\u8bfa'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gsupplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_supplieer', to='ch_supplier.SupplierInfo', verbose_name='\u5236\u9020\u5546'),
        ),
        migrations.AddField(
            model_name='goodsimages',
            name='gimgoods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gim_goods', to='ch_goods.goodsinfo', verbose_name='\u5546\u54c1'),
        ),
        migrations.AddField(
            model_name='goodscount',
            name='gcgoods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ch_goods.goodsinfo', verbose_name='\u5546\u54c1'),
        ),
    ]
