# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-20 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ch_goods', '0002_auto_20180516_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='spic',
            field=models.ImageField(blank=True, null=True, upload_to='ch_goods/size', verbose_name='\u89c4\u683c\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='goodscount',
            name='gcgoods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goods_count', to='ch_goods.goodsinfo', verbose_name='\u5546\u54c1'),
        ),
        migrations.AlterField(
            model_name='goodsimages',
            name='gpic',
            field=models.ImageField(upload_to='ch_goods', verbose_name='\u5546\u54c1\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='goodsmangent',
            name='gmgoods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goods_mangment', to='ch_goods.goodsinfo', verbose_name='\u5546\u54c1'),
        ),
    ]
