# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-20 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ch_goods', '0003_auto_20180520_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='goodsuseinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstitle', models.CharField(max_length=16, verbose_name='\u5546\u54c1\u7528\u9014')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u7528\u9014',
                'verbose_name_plural': '\u5546\u54c1\u7528\u9014\u5217\u8868',
            },
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goodstype',
            field=models.ManyToManyField(related_name='goods', to='ch_goods.goodstype', verbose_name='\u6240\u5c5e\u5546\u54c1\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='ch_goods.packaging', verbose_name='\u5305\u88c5'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gserver',
            field=models.ManyToManyField(related_name='goods', to='ch_goods.server', verbose_name='\u670d\u52a1\u627f\u8bfa'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='goodsuse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='ch_goods.goodsuseinfo', verbose_name='\u7528\u9014'),
        ),
    ]
