# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-23 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ch_goods', '0004_auto_20180520_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='customgoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsprice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u5b9a\u5236\u5355\u4ef7')),
            ],
        ),
        migrations.CreateModel(
            name='paintstyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pstitle', models.CharField(max_length=11, verbose_name='\u7ed8\u753b\u98ce\u683c')),
            ],
            options={
                'verbose_name': '\u7ed8\u753b\u98ce\u683c',
                'verbose_name_plural': '\u7ed8\u753b\u98ce\u683c\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='paintsub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pstitle', models.CharField(max_length=11, verbose_name='\u7ed8\u753b\u9898\u6750')),
            ],
            options={
                'verbose_name': '\u7ed8\u753b\u9898\u6750',
                'verbose_name_plural': '\u7ed8\u753b\u9898\u6750\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='sjion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sjtitle', models.CharField(max_length=11, verbose_name='\u7ec4\u5408\u540d\u79f0')),
                ('sjpic', models.ImageField(blank=True, null=True, upload_to='ch_goods/sjion', verbose_name='\u89c4\u683c\u7ec4\u5408\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u89c4\u683c\u7ec4\u5408',
                'verbose_name_plural': '\u89c4\u683c\u7ec4\u5408\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='goodscount',
            name='gcollection',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u8d2d\u7269\u8f66\u6570'),
        ),
        migrations.AddField(
            model_name='size',
            name='maxsize',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='\u6700\u5927\u5916\u5f62\u5c3a\u5bf8'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='ch_supplier.brand', verbose_name='\u54c1\u724c'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gmaterials',
            field=models.IntegerField(choices=[(1, '\u9ad8\u5cad\u571f'), (2, '\u7c98\u571f'), (3, '\u6c27\u5316\u94dd')], default=1, verbose_name='\u539f\u6599'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gsupplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='ch_supplier.SupplierInfo', verbose_name='\u5236\u9020\u5546'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gtechnique',
            field=models.IntegerField(choices=[(1, '\u624b\u7ed8'), (2, '\u8d34\u82b1'), (3, '\u5f69\u5370'), (8, '\u5176\u5b83')], default=1, verbose_name='\u5de5\u827a'),
        ),
        migrations.AlterField(
            model_name='goodsmangent',
            name='gstatus',
            field=models.IntegerField(choices=[(0, '\u4e0b\u7ebf'), (1, '\u4e0a\u7ebf'), (2, '\u4f17\u7b79')], default=0, verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='sjion',
            name='sjgoods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sjion', to='ch_goods.goodsinfo', verbose_name='\u6240\u5c5e\u5546\u54c1'),
        ),
        migrations.AddField(
            model_name='customgoods',
            name='cgpicstyle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customgoods', to='ch_goods.paintstyle', verbose_name='\u7ed8\u753b\u98ce\u683c'),
        ),
        migrations.AddField(
            model_name='customgoods',
            name='cgpicsub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customgoods', to='ch_goods.paintsub', verbose_name='\u7ed8\u753b\u9898\u6750'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='goodscustom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='ch_goods.customgoods', verbose_name='\u5b9a\u5236'),
        ),
        migrations.AddField(
            model_name='size',
            name='sizejion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='ch_goods.sjion', verbose_name='\u6240\u5c5e\u89c4\u683c\u7ec4\u5408'),
        ),
    ]
